#!/usr/bin/env bash

################################################################################
# Checks that the docs build successfully
#
# Usage:
#     check/build_docs
################################################################################


cd "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$(git rev-parse --show-toplevel)"

cd docs
make html
