#!/usr/bin/env bash

################################################################################
# Runs integration tests on the repository.
#
# Usage:
#     check/pytest-integration [--flags]
################################################################################

# Get the working directory to the repo root.
cd "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$(git rev-parse --show-toplevel)"

# Run pytest
pytest superstaq/*_integration_test.py --ignore=examples/
